### ISSUE TITLE
multiple faces 

### ISSUE THREAD

**Issue by SaiSandeepKantareddy** [Dhruvish-Patel/face_mask_detection#1]
Hi, multiple faces in a single frame are not able to detect?

**Comment by Dhruvish-Patel** [comment]
Yes currently working on it. It is able to detect them if the subjects try to move a little bit. Trying to solve this issue.

**Comment by SaiSandeepKantareddy** [comment]
> Yes currently working on it. It is able to detect them if the subjects try to move a little bit. Trying to solve this issue.

Yes, even I am facing the same problem, I think this is due to open cv dnn problem?

**Comment by Dhruvish-Patel** [comment]
It can be. There's an alternative to tackle this. Instead of using Facenet, we can try the same thing using the Haar Cascades. This issue will get solved using it.

**Comment by SaiSandeepKantareddy** [comment]
That's true I did that but the problem is it is not able to detect the side angle faces that is the reason we have this face net, and anyway I solved the problem  by retraining the face mask detector model  and it is working now.
